services:
  nestjs-optimize-pg-db:
    image: postgres:16.4
    restart: always
    ports:
      - 5439:5432
    environment:
      POSTGRES_USER: some-user
      POSTGRES_PASSWORD: non-important-pg-password
      POSTGRES_DB: dev