services:
  nestjs-optimize-mssql-db-2:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - 1499:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "c0mpLex-5eCreT-paword"
      MSSQL_PID: "Express"  # Optional: Specifies the SQL Server edition
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mounts the init script
